#define MAX_DIM_INPUT               100
#define LEN_BUFFER                  1024
#define MAX_LEN_UTN                 40
#define MAX_LEN_PSW                 20
#define MAX_LEN_MSG                 1024
#define MAX_UTN_INP                 MAX_LEN_UTN+20
#define COMANDO_MESSAGGIO           1
#define COMANDO_LOGIN               40
#define COMANDO_SIGNUP              41
#define COMANDO_TSOUT               42
#define COMANDO_HANGING             43
#define COMANDO_SHOW                44
#define COMANDO_ACK                 45
#define COMANDO_INVIO_FILE          46
#define COMANDO_LISTA               47
#define COMANDO_NUOVA_CONNESIONE    48
#define AGGIUNGI_MEMBRO_GRUPPO      49
#define COMANDO_GRUPPO              50
#define SHOW_NUOVO_MESSAGGIO        1
#define SHOW_FINE                   2
#define FINE_LISTA                  1
#define NUOVA_RIGA_LISTA            2
#define ACCETTO_FILE                1
#define RIFIUTO_FILE                2
#define HANGING_NUOVA_RIGA          1
#define HANGING_FINE                2
#define RISPOSTA_RECAPITO           2
#define RISPOSTA_MEMORIZZAZIONE     1
#define POSIZIONE_TERM_CHAT         1
#define POSIZIONE_TERM_HOME         2
#define ORDINE_SERVER               1
#define ORDINE_DEVICE               2
#define SUCCESS_CODE                200
#define FAIL_CODE                   250
#define UTENTE_INESISTENTE          201
#define TEST_CONNECTION             100